# LOCAL
# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:54322/fincon
spring.datasource.username=admin
spring.datasource.password=1234

#PROD
spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.url=${FINCON_DATABASE_URL}
#spring.datasource.username=${FINCON_DATABASE_USERNAME}
#spring.datasource.password=${FINCON_DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
server.port=8082
#spring.jpa.open-in-view=false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

springdoc.packages-to-scan=com.fincon.controller
springdoc.paths-to-match=/api/**

spring.jackson.time-zone=America/Sao_Paulo

#Evitar o reaproveitamento indevido de prepared statements.
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.auto-commit=false

#spring.jpa.properties.hibernate.jdbc.batch_size=1
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.properties.hibernate.order_inserts=true

#Desativa o cache de Prepared Statements
#spring.jpa.properties.hibernate.cache.use_query_cache=false
